const mongoose = require('mongoose');

// ─── Student Full Notes ────────────────────────────────────────────
// Per-student, per-module comprehensive study notes generated by the
// LLM. Separate from StudentModuleContent (which holds the module
// lesson content). This collection stores the "View Full Notes"
// output — deep, section-based notes with gamified examples.
// ────────────────────────────────────────────────────────────────────

const sectionSchema = new mongoose.Schema(
  {
    heading: { type: String, required: true },
    content: { type: String, required: true },
  },
  { _id: false }
);

const studentFullNotesSchema = new mongoose.Schema(
  {
    studentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    moduleId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Module',
      required: true,
    },
    masteryUsed: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
    title: {
      type: String,
      required: true,
    },
    sections: {
      type: [sectionSchema],
      required: true,
    },
    gamifiedExamples: {
      type: [String],
      default: [],
    },
    generatedAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

// One full-notes document per student per module
studentFullNotesSchema.index(
  { studentId: 1, moduleId: 1 },
  { unique: true }
);

module.exports = mongoose.model('StudentFullNotes', studentFullNotesSchema);
